# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_services import booking_pb2 as app_dot_grpc__services_dot_booking__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/grpc_services/booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBooking = channel.unary_unary(
                '/booking.BookingService/CreateBooking',
                request_serializer=app_dot_grpc__services_dot_booking__pb2.BookingRequest.SerializeToString,
                response_deserializer=app_dot_grpc__services_dot_booking__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.DeleteBooking = channel.unary_unary(
                '/booking.BookingService/DeleteBooking',
                request_serializer=app_dot_grpc__services_dot_booking__pb2.BookingIdRequest.SerializeToString,
                response_deserializer=app_dot_grpc__services_dot_booking__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.GetAllBookings = channel.unary_unary(
                '/booking.BookingService/GetAllBookings',
                request_serializer=app_dot_grpc__services_dot_booking__pb2.Empty.SerializeToString,
                response_deserializer=app_dot_grpc__services_dot_booking__pb2.BookingList.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBooking,
                    request_deserializer=app_dot_grpc__services_dot_booking__pb2.BookingRequest.FromString,
                    response_serializer=app_dot_grpc__services_dot_booking__pb2.BookingResponse.SerializeToString,
            ),
            'DeleteBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBooking,
                    request_deserializer=app_dot_grpc__services_dot_booking__pb2.BookingIdRequest.FromString,
                    response_serializer=app_dot_grpc__services_dot_booking__pb2.BookingResponse.SerializeToString,
            ),
            'GetAllBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBookings,
                    request_deserializer=app_dot_grpc__services_dot_booking__pb2.Empty.FromString,
                    response_serializer=app_dot_grpc__services_dot_booking__pb2.BookingList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booking.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booking.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/CreateBooking',
            app_dot_grpc__services_dot_booking__pb2.BookingRequest.SerializeToString,
            app_dot_grpc__services_dot_booking__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/DeleteBooking',
            app_dot_grpc__services_dot_booking__pb2.BookingIdRequest.SerializeToString,
            app_dot_grpc__services_dot_booking__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetAllBookings',
            app_dot_grpc__services_dot_booking__pb2.Empty.SerializeToString,
            app_dot_grpc__services_dot_booking__pb2.BookingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
