# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc_services/booking.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/grpc_services/booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61pp/grpc_services/booking.proto\x12\x07\x62ooking\">\n\x0e\x42ookingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\"&\n\x10\x42ookingIdRequest\x12\x12\n\nbooking_id\x18\x01 \x01(\x05\"\"\n\x0f\x42ookingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"C\n\x07\x42ooking\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\r\n\x05\x65vent\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"1\n\x0b\x42ookingList\x12\"\n\x08\x62ookings\x18\x01 \x03(\x0b\x32\x10.booking.Booking2\xd2\x01\n\x0e\x42ookingService\x12\x42\n\rCreateBooking\x12\x17.booking.BookingRequest\x1a\x18.booking.BookingResponse\x12\x44\n\rDeleteBooking\x12\x19.booking.BookingIdRequest\x1a\x18.booking.BookingResponse\x12\x36\n\x0eGetAllBookings\x12\x0e.booking.Empty\x1a\x14.booking.BookingListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc_services.booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKINGREQUEST']._serialized_start=44
  _globals['_BOOKINGREQUEST']._serialized_end=106
  _globals['_BOOKINGIDREQUEST']._serialized_start=108
  _globals['_BOOKINGIDREQUEST']._serialized_end=146
  _globals['_BOOKINGRESPONSE']._serialized_start=148
  _globals['_BOOKINGRESPONSE']._serialized_end=182
  _globals['_EMPTY']._serialized_start=184
  _globals['_EMPTY']._serialized_end=191
  _globals['_BOOKING']._serialized_start=193
  _globals['_BOOKING']._serialized_end=260
  _globals['_BOOKINGLIST']._serialized_start=262
  _globals['_BOOKINGLIST']._serialized_end=311
  _globals['_BOOKINGSERVICE']._serialized_start=314
  _globals['_BOOKINGSERVICE']._serialized_end=524
# @@protoc_insertion_point(module_scope)
