# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"e\n\x0ePaymentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nbooking_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x0e\n\x06method\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"&\n\x10PaymentIdRequest\x12\x12\n\npayment_id\x18\x01 \x01(\x05\"3\n\x0fPaymentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty\"}\n\x07Payment\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nbooking_id\x18\x03 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x02\x12\x0e\n\x06method\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\"1\n\x0bPaymentList\x12\"\n\x08payments\x18\x01 \x03(\x0b\x32\x10.payment.Payment2\xd2\x01\n\x0ePaymentService\x12\x42\n\rCreatePayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\x12\x44\n\rDeletePayment\x12\x19.payment.PaymentIdRequest\x1a\x18.payment.PaymentResponse\x12\x36\n\x0eGetAllPayments\x12\x0e.payment.Empty\x1a\x14.payment.PaymentListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTREQUEST']._serialized_start=26
  _globals['_PAYMENTREQUEST']._serialized_end=127
  _globals['_PAYMENTIDREQUEST']._serialized_start=129
  _globals['_PAYMENTIDREQUEST']._serialized_end=167
  _globals['_PAYMENTRESPONSE']._serialized_start=169
  _globals['_PAYMENTRESPONSE']._serialized_end=220
  _globals['_EMPTY']._serialized_start=222
  _globals['_EMPTY']._serialized_end=229
  _globals['_PAYMENT']._serialized_start=231
  _globals['_PAYMENT']._serialized_end=356
  _globals['_PAYMENTLIST']._serialized_start=358
  _globals['_PAYMENTLIST']._serialized_end=407
  _globals['_PAYMENTSERVICE']._serialized_start=410
  _globals['_PAYMENTSERVICE']._serialized_end=620
# @@protoc_insertion_point(module_scope)
